#!/usr/bin/env python3
"""Generate polyphase windowed-sinc FIR coefficients for 44.1 <-> 23.4 kHz.

Emits a C header (resampler_coeffs.h) with two tables:
  - down_coeffs[NUM_PHASES][TAPS]  (44.1 -> 23.4)
  - up_coeffs[NUM_PHASES][TAPS]    (23.4 -> 44.1)

Both directions use a 32-tap Kaiser-windowed sinc.
"""
import math
import sys

TAPS = 32
NUM_PHASES = 256  # finer subsample resolution = lower-frequency phase-quant artifacts
KAISER_BETA = 8.6


def i0(x):
    """Modified Bessel function of the first kind, order 0."""
    sum_ = 1.0
    term = 1.0
    for k in range(1, 50):
        term *= (x / (2.0 * k)) ** 2
        sum_ += term
        if term < 1e-12 * sum_:
            break
    return sum_


def kaiser(n, N, beta):
    return i0(beta * math.sqrt(1 - ((2 * n) / (N - 1) - 1) ** 2)) / i0(beta)


def sinc(x):
    if x == 0.0:
        return 1.0
    return math.sin(math.pi * x) / (math.pi * x)


def kaiser_continuous(x, beta):
    """Kaiser window evaluated at fractional position x in [0, 1]
    (peak at x=0.5, zero at endpoints)."""
    arg = 2.0 * x - 1.0
    return i0(beta * math.sqrt(max(0.0, 1.0 - arg * arg))) / i0(beta)


def gen_table(cutoff_normalized):
    """cutoff_normalized: cutoff frequency relative to source sample rate.

    For phase fraction frac in [0, 1), compute h[k] for k=0..L-1 such that
    convolving input[integer..integer+L-1] with h yields the value at
    output position integer + (L-1)/2 + frac.

    Critically: n = tap - center - frac (NOT + frac). Wrong sign creates
    a phase-error pattern that repeats every NUM_PHASES samples and sounds
    like high-frequency hash modulated by the input signal.
    """
    table = [[0.0] * TAPS for _ in range(NUM_PHASES)]
    L = TAPS
    center = (L - 1) / 2.0
    for phase in range(NUM_PHASES):
        frac = phase / NUM_PHASES
        for tap in range(L):
            n = tap - center - frac
            # Window: fixed Kaiser, smooth across all phases (no offset-dependent
            # discontinuity at the seam between phase 0 and phase 1).
            w = kaiser_continuous((tap + 0.5) / L, KAISER_BETA)
            table[phase][tap] = 2 * cutoff_normalized * sinc(2 * cutoff_normalized * n) * w
    for phase in range(NUM_PHASES):
        s = sum(table[phase])
        if s != 0.0:
            table[phase] = [c / s for c in table[phase]]
    return table


def emit_table(name, table, fp):
    fp.write(f"static const float {name}[{NUM_PHASES}][{TAPS}] = {{\n")
    for row in table:
        coeffs = ", ".join(f"{c:+.10e}f" for c in row)
        fp.write(f"    {{ {coeffs} }},\n")
    fp.write("};\n\n")


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "src/dsp/resampler_coeffs.h"

    down = gen_table(0.45 * (23400.0 / 44100.0))
    up = gen_table(0.45)

    with open(out_path, "w") as fp:
        fp.write("/* Auto-generated by scripts/gen_resampler.py - do not edit. */\n\n")
        fp.write(f"#define RESAMPLER_TAPS {TAPS}\n")
        fp.write(f"#define RESAMPLER_PHASES {NUM_PHASES}\n\n")
        emit_table("down_coeffs", down, fp)
        emit_table("up_coeffs", up, fp)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
